name:
run-name: Talc Evals for ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on: [push]
jobs:
  Test-Talc-AI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          TALC_API_KEY: ${{ secrets.TALC_API_KEY }}
        run: talc upload-and-grade --csv ./artifacts/output.csv --name "Demo test run" --fail_on_error
